### ISSUE TITLE
Layer time

### ISSUE THREAD

**Issue by supermerill** [rongith/PrusaSlicer#3]
Hi
I fixed the layer time gui for 2.3
it's working since supermerill@4d4293c921fc13745bf61cfe375b904402223726
basically, the important bits are
 - //update times for resuts in GcodeProcessor l833
 - remove 0 in gcodeviewer l395
 - use hms in gcodeviewer l2200 / 2368
- log adapt for gcodeviewer l154

**Comment by rongith** [comment]
OK. I will have a look. I was waiting the newest Prusa alpha release to modify my pull request as there are many things changed. But I didn't took the time to do it. Will see if  I can simply take your code and maybe close the pull request.
It is few monthes now I didn't take a look into the code, I'm rusty.
